# Site 
title: EL's Shelf (dev)
description: >- 
  Eryn's reading journal (dev)
baseurl: / 
url: "https://ayeryn.github.io" 
include: ["_pages"]

# Author
author:
  name: EL
  email: test@test.com

# Build
# theme: jekyll-theme-yat
remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-include-cache
github:
  repository: ayeryn/els-shelf-dev


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

collections:
  challenge:
    output: true
    permalink: /:collection/:path/
  review:
    output: true
    permalink: /:collection/:path/

















